#ifndef IPV6_EVENT_H__
#define IPV6_EVENT_H__

typedef enum {
    V6_MONITOR_EVENT_DHCP6_RECONFIG = 1,
    V6_MONITOR_EVENT_ND_PROXY_DISABLE,
    V6_MONITOR_EVENT_ND_PROXY_ENABLE,
    V6_MONITOR_EVENT_RADVD_ENABLE,
    V6_MONITOR_EVENT_RADVD_DISABLE,
    V6_MONITOR_EVENT_PD,
    V6_MONITOR_EVENT_RA,
    V6_MONITOR_EVENT_PT,
} v6_monitor_event_e;

typedef enum {
    NDPROXY_EVENT_DISABLE_RA_PROXY = 1,
    NDPROXY_EVENT_DISABLE_DAD_PROXY,
    NDPROXY_EVENT_ENABLE_RA_PROXY,
    NDPROXY_EVENT_ENABLE_DAD_PROXY,
    NDPROXY_EVENT_DUMP_NEIGHBOR_CACHE_TABLE,
    NDPROXY_EVENT_DUMP_BINDING_TABLE,
    NDPROXY_EVENT_CLEAR_NEIGHBOR_CACHE_TABLE,
    NDPROXY_EVENT_CLEAR_BINDING_TABLE,
} nd_proxy_event_e;

#endif